---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - devops-engineer.com.cn
  resources:
  - upgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops-engineer.com.cn
  resources:
  - upgrades/finalizers
  verbs:
  - update
- apiGroups:
  - devops-engineer.com.cn
  resources:
  - upgrades/status
  verbs:
  - get
  - patch
  - update
